version: '3.8'

services:
  grafana:
    image: ${DOCKER_REGISTRY}/grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    restart: always
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ${GRAFANA_DATA_DIR}:/var/lib/grafana
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./datasources:/etc/grafana/provisioning/datasources
    environment:
      - TZ=${TIMEZONE}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GRAFANA_ALLOW_SIGN_UP}
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=${GRAFANA_AUTO_ASSIGN_ORG_ROLE}
      - GF_INSTALL_PLUGINS=victoriametrics-logs-datasource,grafana-piechart-panel,grafana-worldmap-panel
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=victorialogs-datasource
      - GF_LOG_LEVEL=${GRAFANA_LOG_LEVEL}
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_UNIFIED_ALERTING_ENABLED=true
    networks:
      - vvg-monitoring
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    user: "472"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"

networks:
  vvg-monitoring:
    driver: bridge
    name: ${DOCKER_NETWORK} 