services:
  grafana:
    image: ${GRAFANA_IMAGE}
    container_name: grafana
    restart: always
    stop_grace_period: 1m
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ${GRAFANA_DATA_DIR}:/var/lib/grafana
      - ./dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - TZ=${TIMEZONE}
      - VICTORIALOGS_URL=${VICTORIALOGS_URL}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GRAFANA_ALLOW_SIGN_UP}
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=${GRAFANA_AUTO_ASSIGN_ORG_ROLE}
      - GF_LOG_LEVEL=${GRAFANA_LOG_LEVEL}
      - GF_EXPLORE_DEFAULTTIMEOFFSET=15m
      - GF_PATHS_PLUGINS=/var/lib/grafana-plugins
      - GF_SECURITY_ALLOW_EMBEDDING=${GRAFANA_ALLOW_EMBEDDING}
      - GF_UNIFIED_ALERTING_ENABLED=true
    networks:
      - vvg-monitoring
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:3000/api/health >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 120s
    user: "472"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"

networks:
  vvg-monitoring:
    driver: bridge
    name: ${DOCKER_NETWORK}
