{
 "title": "Gateway 请求日志分析",
 "description": "Kubernetes Gateway access logs collected by Vector, stored in ClickHouse, and visualized in Grafana.",
 "tags": [
  "vector",
  "clickhouse",
  "gateway"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "label": "项目", "query": "show tables" },
   {
    "name": "server_ip",
    "label": "NGINX",
    "query": "SELECT\nconcat(server_ip ,'#server_ip = \\'',server_ip,'\\'') \nfrom $project PREWHERE $__timeFilter(timestamp) \ngroup by server_ip"
   },
   {
    "name": "domain",
    "label": "域名",
    "query": "select\nconcat(domain,'#domain = \\'',domain,'\\'') \nFROM ${project}\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip}\n\tgroup by domain \n\torder by count() desc\n"
   },
   {
    "name": "status",
    "label": "状态",
    "query": "全部 : 1=1, 1XX : status >=100 and status <200, 200 : status = 200, 2XX : status >=200 and status <300, 3XX : status >=300 and status <400, 4XX : status >=400 and status <500, 5XX : status >=500 and status <600"
   },
   {
    "name": "uri",
    "label": "指定接口分析",
    "query": "select path FROM ${project}\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}  and ${status}\n\tgroup by path\n\torder by count() desc\nlimit 100\n"
   },
   {
    "name": "cip",
    "label": "指定用户IP分析",
    "query": "select client_ip FROM ${project}\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}  and ${status}\n\tgroup by client_ip\n\torder by count() desc\nlimit 100\n"
   },
   {
    "name": "cal_interval",
    "label": "计算间隔",
    "query": "1s : 1, 10s : 10, 15s : 15, 30s : 30, 1m : 60,5m : 300, 10m : 600, 30m : 1800, 1h : 3600 "
   }
  ]
 },
 "panels": [
  { "title": "全局", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "各域名平均响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"平均\",domain\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip}\r\nGROUP BY time,domain\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "各域名整体QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS avgqps, domain\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip}\r\n\tGROUP BY time,domain\r\n  order by time"
    }
   ]
  },
  {
   "title": "各域名请求PV占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n    domain,\r\n    COUNT()\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip}\r\n\tGROUP BY domain\r\n  order by COUNT() DESC"
    }
   ]
  },
  {
   "title": "各域名请求UV占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n    domain,\r\n    COUNT(DISTINCT client_ip)\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and  ${server_ip}\r\n\tGROUP BY domain\r\n  order by COUNT() DESC"
    }
   ]
  },
  { "title": "请求与耗时分析【$domain】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, sum(request_length) * 8 / ${cal_interval} as \"今日最大请求量\"\r\nFROM ${project}\r\nPREWHERE toDate(timestamp) = today() and ${server_ip} and ${domain}\r\nGROUP BY time\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, sum(response_length) * 8 / ${cal_interval} as \"今日最大返回量\"\r\n\tFROM ${project}\r\n\tPREWHERE toDate(timestamp) = today() and ${server_ip} and ${domain}\r\nGROUP BY time\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS \"今日最大QPS\"\r\n\tFROM ${project}\r\n\tPREWHERE toDate(timestamp) = today() and ${server_ip} and ${domain}\r\n\tGROUP BY time\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,countIf(status<400)/count() *100 as \"请求成功率\"\r\nFROM ${project} \r\nPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\ngroup by time\r\norder by time\r\n"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count()/${cal_interval} AS \"当前QPS\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\n\tGROUP BY time\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"整体响应时间\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT count()/10000 as \"今日总PV(万)\"\r\nFROM ${project}\r\n\tPREWHERE toDate(timestamp) = today() and ${server_ip} and ${domain}"
    },
    {
     "rawSql": "\tSELECT COUNT(DISTINCT client_ip) AS \"今日总UV\"\r\n\tFROM ${project}\r\n\tPREWHERE toDate(timestamp) = today() and ${server_ip} and ${domain}\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE\r\n        WHEN status >= 100 AND status < 200 THEN '1XX'     \r\n        WHEN status >= 200 AND status < 300 THEN '2XX'\r\n        WHEN status >= 300 AND status < 400 THEN '3XX'\r\n        WHEN status >= 400 AND status < 500 THEN '4XX'\r\n        WHEN status >= 500 AND status < 600 THEN '5XX'\r\n        ELSE 'Other'\r\n    END AS status_category,\r\n    COUNT(*) AS count\r\nFROM ${project}\r\nPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\nGROUP BY \r\n    status_category\r\norder BY\r\n    status_category"
    }
   ]
  },
  {
   "title": "HTTP${status} QPS与每分钟UV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 60 SECOND) AS time, COUNT(DISTINCT client_ip) AS \"每分钟UV\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS \"QPS\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "HTTP${status}响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.99)(responsetime) as P99\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.90)(responsetime) as P90\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.50)(responsetime) as P50\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.75)(responsetime) as P75\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.95)(responsetime) as P95\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"平均\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  `top_path` as TOP_Path, COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\",avg(response_length) as \"平均返回\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\n\tGROUP BY `top_path`\r\n  order by COUNT() DESC\r\n"
    },
    {
     "rawSql": "\tSELECT\r\n\t  `top_path` as TOP_Path,avg(responsetime) as \"指定状态响应时间\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY `top_path`"
    },
    {
     "rawSql": "SELECT `top_path` as TOP_Path,\r\ncountIf(status >=400 and status < 500) as 4XX,\r\ncountIf(status>=500) as 5XX\r\nFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\nGROUP BY \r\n    `top_path`"
    }
   ]
  },
  {
   "title": "各后端HTTP${status} QPS占比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "各后端HTTP${status} QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS avgqps, upstreamhost\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time,upstreamhost\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS avgqps, '整体'\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "各后端HTTP${status}平均响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as rt,'整体'\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,upstreamhost,avg(responsetime) as rt\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time,upstreamhost\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "HTTP${status}耗时分布",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n    CASE\r\n        WHEN responsetime >= 0 AND responsetime <= 0.01 THEN '0-10'\r\n        WHEN responsetime > 0.01 AND responsetime <= 0.025 THEN '0-25'\r\n        WHEN responsetime > 0.025 AND responsetime <= 0.05 THEN '1-50'\r\n        WHEN responsetime > 0.05 AND responsetime <= 0.1 THEN '2-100'\r\n        WHEN responsetime > 0.1 AND responsetime <= 0.15 THEN '3-150'\r\n        WHEN responsetime > 0.15 AND responsetime <= 0.2 THEN '4-200'\r\n        WHEN responsetime > 0.2 AND responsetime <= 0.3 THEN '5-300'\r\n        WHEN responsetime > 0.3 AND responsetime <= 0.5 THEN '6-500'\r\n        WHEN responsetime > 0.5 AND responsetime <= 1 THEN '7-1000'\r\n        ELSE 'N-MAX'\r\n    END AS status_category,\r\n    COUNT() AS count\r\nFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY \r\n    time,status_category\r\norder BY\r\n    time,status_category"
    }
   ]
  },
  {
   "title": "HTTP${status}请求方法占比",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  request_method, \r\n    COUNT()\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY request_method\r\n  order by COUNT() DESC"
    }
   ]
  },
  {
   "title": "各NGINX HTTP${status} QPS占比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "各NGINX HTTP${status} QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, server_ip, count() / ${cal_interval} AS avgqps\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time,server_ip\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS avgqps,'整体'\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "各NGINX平均响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as rt, '整体'\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,server_ip,avg(responsetime) as rt\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time,server_ip\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "HTTP${status}每小时PV与UV(最近25h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfHour(timestamp) AS time, count() AS \"每小时PV\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfHour(timestamp) AS time, COUNT(DISTINCT client_ip) AS \"每小时UV\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "HTTP${status}请求与返回量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, sum(request_length) * 8 / ${cal_interval} as \"每秒请求量\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, sum(response_length) * 8 / ${cal_interval} as \"每秒返回量\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  { "title": "异常请求分析【$domain】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "TOP_Path HTTP异常状态码(每分钟累计值)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) as time,\r\n  count() as value,top_path,toString(status) as \"状态\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and status >= 500\r\nGROUP BY time,status,top_path\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "HTTP异常状态码(每分钟同一URI累计>10次)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) as time,\r\n  count() as count,path\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and status >= 500\r\nGROUP BY time,path\r\nhaving count >= 10\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "每分钟非HTTP200的请求数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 60 SECOND) AS time,toString(status), count(status)  AS HTTP\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and status != 200\r\n\tGROUP BY time,status\r\n  order by time"
    }
   ]
  },
  {
   "title": "每10分钟程序请求数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 10 MINUTE) AS time, COUNT() as \"应用\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and (http_user_agent like '%Java%' OR http_user_agent like '%python%')\r\n\tGROUP BY time\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL 10 MINUTE) AS time, COUNT() as \"爬虫\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and (http_user_agent like '%spider%' OR http_user_agent like '%bot%')\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "TOP_Path每分钟耗时大于500ms的请求数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfMinute(timestamp) AS time, top_path\r\n\t, countIf(responsetime > 0.5) AS slow_requests\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\nGROUP BY time, top_path\r\nHAVING slow_requests > 0\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "TOP_Path大于500ms请求，占整体大于500ms请求的比例",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "请求域名平均响应时间",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n\tdomain as \"域名\",avg(responsetime) as \"响应时间\", count() as PV,COUNT(DISTINCT client_ip) as UV\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\n\tGROUP BY domain"
    }
   ]
  },
  {
   "title": "请求耗时最慢TOP30（PV>100）",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  `path` as \"请求路径\", avg(responsetime) as \"平均响应时间\",COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\",avg(response_length) as \"平均返回量\"\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\n\tGROUP BY `path`\r\n\tHAVING PV >100\r\n\torder by \"平均响应时间\" DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  {
   "title": "P90 NGINX处理耗时最慢 TOP30（PV>10）",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  `path` as \"请求路径\",quantileExact(0.90)(duration) as \"P90NG处理时间\",avg(response_length) as \"平均返回量\", avg(responsetime) as \"平均响应时间\",COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\n\tGROUP BY `path`\r\n\tHAVING PV > 10\r\n\torder by \"P90NG处理时间\" DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  { "title": "URI请求分析【$domain】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "TOP_Path HTTP${status}平均响应时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"平均\",top_path\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time,top_path\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "TOP_Path HTTP${status} QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, top_path, count() / ${cal_interval} AS avgqps\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time, top_path\r\n  order by time"
    }
   ]
  },
  {
   "title": "TOP_Path HTTP${status} P90响应时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,quantileExact(0.90)(responsetime) as P90,top_path\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time,top_path\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "TOP_Path每分钟返回数据量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfMinute(timestamp) AS time, top_path,sum(response_length) as \"返回量\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\nGROUP BY time, top_path\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "HTTP${status}请求来源TOP30",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  referer as Referer, \r\n    COUNT() as \"PV\", COUNT(DISTINCT client_ip) as \"UV\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY referer\r\n  order by COUNT() DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  {
   "title": "HTTP${status}各URI请求数TOP30",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  `path` as \"请求路径\", COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\",avg(responsetime) as \"平均响应时间\",avg(response_length) as \"平均返回量\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY `path`\r\n  order by PV DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  {
   "title": "HTTP${status}返回数据量TOP30",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  `path` as \"请求路径\",avg(response_length) as \"平均返回量\", avg(responsetime) as \"平均响应时间\",COUNT() AS PV, COUNT(DISTINCT client_ip) as \"UV\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY `path`\r\n  order by \"平均返回量\" DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  { "title": "用户与地域分析【$domain】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "HTTP${status} 用户IP请求量 TOP30",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_ip as \"用户IP\", \r\n    COUNT() AS PV, COUNT(DISTINCT `path`) as \"请求URL数\",sum(response_length) as \"接收数据量\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY client_ip\r\n  order by PV DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  {
   "title": "最近1分钟各城市HTTP${status}平均响应时间与PV",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT client_region as \"省份\",client_city as \"城市\",avg(responsetime) as \"响应时间\",count() as \"PV\",COUNT(DISTINCT client_ip) as UV\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\ngroup by client_region,client_city"
    }
   ]
  },
  {
   "title": "HTTP${status}请求省份占比",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_region, \r\n    COUNT() AS \"未解析\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY client_region"
    }
   ]
  },
  {
   "title": "HTTP${status}请求城市占比",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_city, \r\n    COUNT() AS \"未解析\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY client_city"
    }
   ]
  },
  {
   "title": "请求操作系统占比",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_os_family, \r\n    COUNT() AS \"未解析\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain}\r\n\tGROUP BY client_os_family\r\n"
    }
   ]
  },
  {
   "title": "请求浏览器TOP10",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_browser_family, \r\n    COUNT() AS \"未解析\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY client_browser_family\r\n  order by COUNT() DESC\r\n\tLIMIT 10;"
    }
   ]
  },
  {
   "title": "请求设备型号TOP10",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_device_model, \r\n    COUNT() AS \"总数\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_device_model != ''\r\n\tGROUP BY client_device_model\r\n  order by COUNT() DESC\r\n\tLIMIT 10;"
    }
   ]
  },
  {
   "title": "请求设备品牌TOP10",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_device_brand, \r\n    COUNT() AS \"总数\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_device_brand != ''\r\n\tGROUP BY client_device_brand\r\n  order by COUNT() DESC\r\n\tLIMIT 10;"
    }
   ]
  },
  {
   "title": "各城市HTTP${status}QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 112 },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, client_city, count() / ${cal_interval} AS avgqps\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY time,client_city\r\n  order by time"
    }
   ]
  },
  {
   "title": "各城市HTTP200平均响应时间(QPS>1)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"平均\",client_city\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time,client_city\r\nhaving count()/${cal_interval} > 1\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "HTTP200 P90响应时间(QPS>1)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,quantileExact(0.90)(responsetime) as P90,client_city\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\nGROUP BY time,client_city\r\nhaving count()/${cal_interval} > 1\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "时段HTTP${status}请求数分布",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT COUNT() AS PV, client_latitude as latitude ,client_longitude as longitude,client_city as \"城市\",client_region as \"省份\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY client_latitude,client_longitude,client_city,client_region"
    }
   ]
  },
  {
   "title": "最近5分钟HTTP${status}平均响应延迟分布",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT avg(responsetime) as \"响应时间\", client_latitude as latitude ,client_longitude as longitude,client_city as \"城市\",client_region as \"省份\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status}\r\n\tGROUP BY client_latitude,client_longitude,client_region,client_city"
    }
   ]
  },
  {
   "title": "指定用户IP分析：${cip}【$domain】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 },
   "collapsed": true,
   "panels": [
    {
     "title": "各后端HTTP${status} QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, upstreamhost, count() / ${cal_interval} AS qps\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\n\tGROUP BY time,upstreamhost\r\n  order by time"
      },
      {
       "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS qps,'整体'\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\n\tGROUP BY time\r\n  order by time"
      }
     ]
    },
    {
     "title": "HTTP${status}响应时间",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 7, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.99)(responsetime) as P99\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
      },
      {
       "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.90)(responsetime) as P90\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
      },
      {
       "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.50)(responsetime) as P50\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
      },
      {
       "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.75)(responsetime) as P75\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
      },
      {
       "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.95)(responsetime) as P95\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
      },
      {
       "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"平均\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}'\r\nGROUP BY time\r\nORDER BY time"
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n\t  `top_path` as TOP_Path, COUNT() AS PV,avg(response_length) as \"平均返回\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}'\r\n\tGROUP BY `top_path`\r\n  order by COUNT() DESC\r\n"
      },
      {
       "rawSql": "\tSELECT\r\n\t  `top_path` as TOP_Path,avg(responsetime) as \"指定状态响应时间\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}' \r\n\tGROUP BY `top_path`"
      },
      {
       "rawSql": "SELECT `top_path` as TOP_Path,\r\ncountIf(status >=400 and status < 500) as 4XX,\r\ncountIf(status>=500) as 5XX\r\nFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}'\r\nGROUP BY \r\n    `top_path`"
      }
     ]
    },
    {
     "title": "HTTP状态码统计(每分钟累计)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) as time,\r\n  count() as value,toString(status) as \"状态\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}'\r\nGROUP BY time,status\r\nORDER BY time\r\n"
      }
     ]
    },
    {
     "title": "HTTP${status}请求明细TOP100",
     "type": "table",
     "gridPos": { "h": 20, "w": 19, "x": 5, "y": 150 },
     "targets": [
      {
       "rawSql": "\r\nSELECT timestamp, status, request_method, domain,path,query,server_ip,upstreamhost,responsetime,upstreamtime,request_length,response_length\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and client_ip = '${cip}' \r\n\r\norder by timestamp desc\r\nlimit 100\r\n"
      }
     ]
    },
    {
     "title": "IP地域与设备",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n    client_region,client_city\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}'\r\ngroup by client_region,client_city\r\nlimit 1"
      },
      {
       "rawSql": "\tSELECT\r\n    client_os_family\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}' and client_os_family != ''\r\ngroup by client_os_family\r\n"
      }
     ]
    },
    {
     "title": "各UA PV占比",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 2, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n    count() as count, http_user_agent as UA\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}'\r\n\tGROUP BY http_user_agent\r\n\torder by count desc"
      }
     ]
    },
    {
     "title": "当前时段指定IP各UA PV",
     "type": "table",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "\tSELECT\r\n    COUNT() AS PV, COUNT(DISTINCT `path`) as \"请求URL数\",avg(responsetime) as \"平均响应\",sum(response_length) as \"接收数据量\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and client_ip = '${cip}'\r\n\tGROUP BY client_region,client_city,http_user_agent"
      }
     ]
    }
   ]
  },
  { "title": "指定接口分析：$uri【$domain】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "各后端HTTP${status} QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, upstreamhost, count() / ${cal_interval} AS qps\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\n\tGROUP BY time,upstreamhost\r\n  order by time"
    },
    {
     "rawSql": "\tSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time, count() / ${cal_interval} AS qps,'整体'\r\n\tFROM ${project}\r\n\tWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\n\tGROUP BY time\r\n  order by time"
    }
   ]
  },
  {
   "title": "HTTP${status}响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.99)(responsetime) as P99\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.90)(responsetime) as P90\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.50)(responsetime) as P50\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.75)(responsetime) as P75\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "\r\nSELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,\r\n  quantileExact(0.95)(responsetime) as P95\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as \"平均\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "各后端HTTP${status}平均响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,upstreamhost,avg(responsetime) as rt\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time,upstreamhost\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT toStartOfInterval(timestamp, INTERVAL ${cal_interval} SECOND) AS time,avg(responsetime) as rt, '整体'\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "HTTP状态码统计(每分钟累计)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) as time,\r\n  count() as value,toString(status) as \"状态\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\nGROUP BY time,status\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "【$uri】HTTP${status}请求明细TOP100（本页所有图表均关联该接口）",
   "type": "table",
   "gridPos": { "h": 19, "w": 20, "x": 4, "y": 150 },
   "targets": [
    {
     "rawSql": "  SELECT\r\n      timestamp,\r\n      domain,\r\n      status,\r\n      request_method,\r\n      responsetime,\r\n      client_ip,\r\n      client_city,\r\n      app_id,\r\n      tenant_id,\r\n      platform_id,\r\n      version,\r\n      upstreamhost,\r\n      server_ip,\r\n      upstreamtime,\r\n      request_length,\r\n      response_length,\r\n      query\r\n  FROM ${project}\r\n  PREWHERE $__timeFilter(timestamp)\r\n      and ${server_ip}\r\n      and ${domain}\r\n      and ${status}\r\n      and path='${uri}'\r\n  ORDER BY timestamp DESC\r\n  LIMIT 100"
    }
   ]
  },
  {
   "title": "HTTP${status}请求用户IP TOP30",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "\tSELECT\r\n\t  client_ip as \"用户IP\", \r\n    COUNT() AS PV, avg(responsetime) as \"平均响应时间\"\r\n\tFROM ${project}\r\n\tPREWHERE $__timeFilter(timestamp) and ${server_ip} and ${domain} and ${status} and path='${uri}'\r\n\tGROUP BY client_ip\r\n  order by PV DESC\r\n\tLIMIT 30;"
    }
   ]
  },
  { "title": "请求日志明细【$domain】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 } },
  {
   "title": "HTTP${status}请求明细（最近500条）",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 170 },
   "targets": [
    {
     "rawSql": "  SELECT\r\n      timestamp,\r\n      domain,\r\n      path,\r\n      status,\r\n      business_code,\r\n      request_method,\r\n      responsetime,\r\n      client_ip,\r\n      client_city,\r\n      user_id,\r\n      user_type,\r\n      app_id,\r\n      tenant_id,\r\n      platform_id,\r\n      version,\r\n      upstreamhost,\r\n      server_ip,\r\n      upstreamtime,\r\n      request_length,\r\n      response_length,\r\n      query\r\n  FROM ${project}\r\n  PREWHERE $__timeFilter(timestamp)\r\n      and ${server_ip}\r\n      and ${domain}\r\n      and ${status}\r\n  ORDER BY timestamp DESC\r\n  LIMIT 500"
    }
   ]
  }
 ]
}