services:
  victorialogs:
    image: ${DOCKER_REGISTRY}/victoriametrics/victoria-logs:${VICTORIALOGS_VERSION}
    container_name: victorialogs
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 2m
    cpus: ${VICTORIALOGS_CPUS}
    mem_limit: ${VICTORIALOGS_MEMORY_LIMIT}
    ports:
      - "${VICTORIALOGS_PORT}:9428"
    volumes:
      - ${VICTORIALOGS_DATA_DIR}:/victoria-logs-data
    environment:
      - TZ=${TIMEZONE}
    command:
      - '--storageDataPath=/victoria-logs-data'
      - '--httpListenAddr=:9428'
      - '--retentionPeriod=${VICTORIALOGS_RETENTION}'
      - '--loggerFormat=json'
      - '--loggerOutput=stderr'
      - '--search.maxConcurrentRequests=${VL_SEARCH_MAX_CONCURRENT_REQUESTS}'
      - '--search.maxQueueDuration=${VL_SEARCH_MAX_QUEUE_DURATION}'
      - '--defaultParallelReaders=${VL_DEFAULT_PARALLEL_READERS}'
      - '--search.maxQueryDuration=${VL_SEARCH_MAX_QUERY_DURATION}'
      - '--search.logSlowQueryDuration=${VL_SEARCH_SLOW_QUERY_DURATION}'
    networks:
      - vvg-monitoring
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"

networks:
  vvg-monitoring:
    driver: bridge
    name: ${DOCKER_NETWORK}
