{
 "title": "AutoMQ Production Cluster",
 "tags": [
  "automq",
  "production"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "cluster_id",
    "query": {
     "query": "label_values(kafka_broker_active_count,job)"
    }
   },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "active_controller",
    "label": "Active Controller",
    "query": {
     "query": "query_result(kafka_controller_active_count{job=\"$cluster_id\"} > 0)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (kafka_controller_active_count{job=\"$cluster_id\"})",
     "legendFormat": "Active Controller"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_broker_fenced_count{job=\"$cluster_id\", instance=\"$active_controller\"}",
     "legendFormat": "Fenced Broker"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_count{job=\"$cluster_id\", instance=\"$active_controller\"}",
     "legendFormat": "Topics"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_request_error_count_total{job=\"$cluster_id\", error!=\"NONE\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes In (+) / Out (-)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_broker_network_io_bytes_total{job=\"$cluster_id\", direction=\"in\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(kafka_broker_network_io_bytes_total{job=\"$cluster_id\", direction=\"out\"}[$__rate_interval])) * -1",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_broker_active_count{job=\"$cluster_id\", instance=\"$active_controller\"}",
     "legendFormat": "Active Broker"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_partition_total_count{job=\"$cluster_id\", instance=\"$active_controller\"}",
     "legendFormat": "Partitions"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by(topic, partition) (kafka_log_size{job=\"$cluster_id\"}))",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Group Count",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_group_count{job=\"$cluster_id\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(kafka_group_stable_count{job=\"$cluster_id\"})",
     "legendFormat": "stable"
    },
    {
     "expr": "sum(kafka_group_dead_count{job=\"$cluster_id\"})",
     "legendFormat": "dead"
    },
    {
     "expr": "sum(kafka_group_empty_count{job=\"$cluster_id\"})",
     "legendFormat": "empty"
    },
    {
     "expr": "sum(kafka_group_preparing_rebalance_count{job=\"$cluster_id\"})",
     "legendFormat": "prepare_rebalance"
    },
    {
     "expr": "sum(kafka_group_completing_rebalance_count{job=\"$cluster_id\"})",
     "legendFormat": "completing_rebalance"
    }
   ]
  },
  {
   "title": "Group Statistics",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 5, "y": 12 },
   "targets": [
    {
     "expr": "sum by(consumer_group, topic) (max by(consumer_group, topic, partition) (kafka_group_commit_offset{job=\"$cluster_id\"}))",
     "legendFormat": "{{consumer_group}}-{{topic}}-{{partition}}"
    },
    {
     "expr": "sum by(topic) (max by(topic, partition) (kafka_log_end_offset{job=\"$cluster_id\"}))",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Topic Statistics",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", direction=\"in\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(topic) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", direction=\"out\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(topic) (rate(kafka_message_count_total{job=\"$cluster_id\", direction=\"in\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(topic) (kafka_log_size{job=\"$cluster_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Statistics",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_partition_count{job=\"$cluster_id\"})"
    },
    {
     "expr": "sum by(instance) (kafka_server_connection_count{job=\"$cluster_id\"})"
    },
    {
     "expr": "sum by(instance) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", direction=\"in\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(instance) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", direction=\"out\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(instance) (rate(kafka_message_count_total{job=\"$cluster_id\", direction=\"in\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(instance) (rate(kafka_request_count_total{job=\"$cluster_id\", type=\"Produce\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(instance) (rate(kafka_request_count_total{job=\"$cluster_id\", type=\"Fetch\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(instance) (kafka_request_time_99p_milliseconds{job=\"$cluster_id\", type=\"Produce\"})"
    },
    {
     "expr": "sum by(instance) (kafka_request_time_99p_milliseconds{job=\"$cluster_id\", type=\"Fetch\"})"
    },
    {
     "expr": "sum by(instance) (rate(kafka_topic_request_failed_total{job=\"$cluster_id\", type=\"produce\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(instance) (rate(kafka_topic_request_failed_total{job=\"$cluster_id\", type=\"fetch\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(instance) (rate(kafka_request_error_count_total{job=\"$cluster_id\", error!=\"NONE\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}